fix MUSIC testing: suppress cp exit code

diff --git a/testsuite/do_tests.sh.in b/testsuite/do_tests.sh.in
--- a/testsuite/do_tests.sh.in
+++ b/testsuite/do_tests.sh.in
@@ -639,8 +639,9 @@ if test "x$(sli -c 'statusdict/have_music :: =')" = xtrue ; then
         echo          "Running test '${test_name}' with $np $proc_txt... " >> "${TEST_LOGFILE}"
         printf '%s' "  Running test '${test_name}' with $np $proc_txt... "
 
-        # Copy everything to the tmpdir.
-        cp "${music_file}" "${sh_file}" "${sli_files}" "${tmpdir}"
+        # Copy everything to the tmpdir. Not all files have to exist and therefore variables can also be empty.
+        # To prevent 'cp' from terminating, exit code and error message is suppressed.
+        cp "${music_file}" "${sh_file}" "${sli_files}" "${tmpdir}" 2>/dev/null || :
         cd "${tmpdir}"
 
         # Create the runner script
