New version of mpirun command
* The new version also takes the name of the executable to run instead of hard-coding $PREFIX/bin/nest
* Adapt the testsuite runner to check for the new version
* Adapt the Travis CI build script to not define mpirun by itself, but use the provided version
* Adapt the unittest and processes library to correctly call the new version

diff --git a/testsuite/do_tests.sh.in b/testsuite/do_tests.sh.in
--- a/testsuite/do_tests.sh.in
+++ b/testsuite/do_tests.sh.in
@@ -517,6 +517,24 @@ echo "--------------------------"
 if test "x$(sli -c 'statusdict/have_mpi :: =')" = xtrue ; then
     junit_open 'core.phase_5'
 
+    # Check for old version of the /mpirun command, which had the NEST executable hardcoded
+    if test "x$(sli -c '/mpirun load cva_t Flatten length 3 eq =')" = xtrue ; then
+	echo "  Unable to run MPI tests because ~/.nestrc contains an old definition of"
+	echo "  /mpirun. If you are using the standard definition, please replace it by"
+	echo
+	echo "  /mpirun"
+	echo "  [/integertype /stringtype /stringtype]"
+	echo "  [/numproc     /executable /scriptfile]"
+	echo "  {"
+	echo "   () ["
+	echo "    (mpirun -np ) numproc cvs ( ) executable ( ) scriptfile"
+	echo "   ] {join} Fold"
+	echo "  } Function def"
+	echo
+        echo
+	exit 1
+    fi
+
     NEST_BINARY=nest_indirect
     for test_name in $(ls "${TEST_BASEDIR}/mpi_selftests/pass" | grep '.*\.sli$') ; do
         run_test "mpi_selftests/pass/${test_name}" "${CODES_SUCCESS}" "${CODES_FAILURE}"
