Update buildmatrixtest1.yml

diff --git a/.github/workflows/buildmatrixtest1.yml b/.github/workflows/buildmatrixtest1.yml
--- a/.github/workflows/buildmatrixtest1.yml
+++ b/.github/workflows/buildmatrixtest1.yml
@@ -1,15 +1,15 @@
 name: test matrix
 env:
-  xGSL: "0"
-  xLIBBOOST: "0"
-  xLIBNEUROSIM: "0"
-  xLTDL: "0"
-  xMPI: "0"
-  xMUSIC: "0"
-  xOPENMP: "0"
-  xPYTHON: "0"
-  xREADLINE: "0"
-  xSIONLIB: "0"
+  #xGSL: "0"
+  #xLIBBOOST: "0"
+  #xLIBNEUROSIM: "0"
+  #xLTDL: "0"
+  #xMPI: "0"
+  #xMUSIC: "0"
+  #xOPENMP: "0"
+  #xPYTHON: "0"
+  #xREADLINE: "0"
+  #xSIONLIB: "0"
   CXX_FLAGS: "-pedantic -Wextra -Woverloaded-virtual -Wno-unknown-pragmas"
 on: push
 jobs:
@@ -30,18 +30,18 @@ jobs:
              TARGET: x86_64-apple-darwin
              COMPILER: clang
              LINKER: clang
-             xNEST_BUILD_TYPE: "STATIC_CODE_ANALYSIS"
+             #xNEST_BUILD_TYPE: "STATIC_CODE_ANALYSIS"
            - os: ubuntu-latest
              TARGET: armv7-unknown-linux-musleabihf
              COMPILER: arm-linux-gnueabihf-gcc-5
              LINKER: gcc-5-arm-linux-gnueabihf
-             xNEST_BUILD_TYPE: "STATIC_CODE_ANALYSIS"
+             #xNEST_BUILD_TYPE: "STATIC_CODE_ANALYSIS"
            - os: ubuntu-latest
              TARGET: x86_64-unknown-linux-musl
              COMPILER: gcc
              LINKER: gcc
              #xNEST_BUILD_TYPE: "STATIC_CODE_ANALYSIS"
-             xNEST_BUILD_TYPE: "MINIMAL"
+             #xNEST_BUILD_TYPE: "MINIMAL"
              
        #- name: MacOS
          #os: [ubuntu-latest, macos-latest]
@@ -94,13 +94,120 @@ jobs:
             pip list
             g++ --version
             set -o pipefail
-            chmod +x extras/staticbuild.sh
-            ./extras/staticbuild.sh
+            #chmod +x extras/staticbuild.sh
+            #./extras/staticbuild.sh
             
-       - if: ${{ matrix.xNEST_BUILD_TYPE == 'MPI_ONLY' }}
+       - if: ${{ matrix.xNEST_BUILD_TYPE == 'STATIC_CODE_ANALYSIS' }}
          #run: echo "MPI Only Build"
          #with: ${{ env.xMPI }}
-         run: ./extras/staticbuild.sh
+         run: |
+           #chmod +x extras/staticbuild.sh
+           #./extras/staticbuild.sh
+           echo "+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +"
+           echo "+               S T A T I C   C O D E   A N A L Y S I S                       +"
+           echo "+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +"
+
+           echo "MSGBLD0010: Initializing VERA++ static code analysis."
+           wget --no-verbose https://bitbucket.org/verateam/vera/downloads/vera++-1.3.0.tar.gz
+           tar -xzf vera++-1.3.0.tar.gz
+           cd vera++-1.3.0
+           cmake -DCMAKE_INSTALL_PREFIX=/usr -DVERA_LUA=OFF -DVERA_USE_SYSTEM_BOOST=ON
+           sudo make install
+           cd -
+           rm -fr vera++-1.3.0 vera++-1.3.0.tar.gz
+           # Add the NEST profile to the VERA++ profiles.
+           sudo cp extras/vera++.profile /usr/lib/vera++/profiles/nest
+           echo "MSGBLD0020: VERA++ initialization completed."
+           if [ ! -f "$HOME/.cache/bin/cppcheck" ]; then
+              echo "MSGBLD0030: Installing CPPCHECK version 1.69."
+              # Build cppcheck version 1.69
+              git clone https://github.com/danmar/cppcheck.git
+              cd cppcheck
+              git checkout tags/1.69
+              mkdir -p install
+              make PREFIX=$HOME/.cache CFGDIR=$HOME/.cache/cfg HAVE_RULES=yes install
+             cd -
+             echo "MSGBLD0040: CPPCHECK installation completed."
+
+             echo "MSGBLD0050: Installing CLANG-FORMAT."
+             wget --no-verbose http://llvm.org/releases/3.6.2/clang+llvm-3.6.2-x86_64-linux-gnu-ubuntu-14.04.tar.xz
+             tar xf clang+llvm-3.6.2-x86_64-linux-gnu-ubuntu-14.04.tar.xz
+             # Copy and not move because '.cache' may aleady contain other subdirectories and files.
+             cp -R clang+llvm-3.6.2-x86_64-linux-gnu-ubuntu-14.04/* $HOME/.cache
+             echo "MSGBLD0060: CLANG-FORMAT installation completed."
+
+             # Remove these directories, otherwise the copyright-header check will complain.
+             rm -rf cppcheck clang+llvm-3.6.2-x86_64-linux-gnu-ubuntu-14.04
+           fi
+
+           # Ensure that the cppcheck and clang-format installation can be found.
+           export PATH=$HOME/.cache/bin:$PATH
+
+           echo "MSGBLD0070: Retrieving changed files."
+           # Note: BUG: Extracting the filenames may not work in all cases.
+           #            The commit range might not properly reflect the history.
+           #            see https://github.com/travis-ci/travis-ci/issues/2668
+           #if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
+              #echo "MSGBLD0080: PULL REQUEST: Retrieving changed files using git diff against $TRAVIS_BRANCH."
+              #file_names=`git diff --name-only --diff-filter=AM $TRAVIS_BRANCH...HEAD`
+           #else
+              #echo "MSGBLD0090: Retrieving changed files using git diff in range $TRAVIS_COMMIT_RANGE."
+              #file_names=`git diff --name-only $TRAVIS_COMMIT_RANGE`
+           #fi
+           #GET CHANGED FILES
+           # https://github.com/marketplace/actions/get-changed-files
+
+           # Note: uncomment the following line to static check *all* files, not just those that have changed.
+           # Warning: will run for a very long time (will time out on Travis CI instances)
+
+           # file_names=`find . -name "*.h" -o -name "*.c" -o -name "*.cc" -o -name "*.hpp" -o -name "*.cpp" -o -name "*.py"`
+
+           for single_file_name in $file_names
+           do
+             echo "MSGBLD0095: File changed: $single_file_name"
+           done
+             echo "MSGBLD0100: Retrieving changed files completed."
+           echo
+
+           # Set the command line arguments for the static code analysis script and execute it.
+
+           # The names of the static code analysis tools executables.
+           VERA=vera++
+           CPPCHECK=cppcheck
+           CLANG_FORMAT=clang-format
+           PEP8=pep8
+
+           # Perform or skip a certain analysis.
+           PERFORM_VERA=true
+           PERFORM_CPPCHECK=true
+           PERFORM_CLANG_FORMAT=true
+           PERFORM_PEP8=true
+
+           # The following command line parameters indicate whether static code analysis error messages
+           # will cause the Travis CI build to fail or are ignored.
+           IGNORE_MSG_VERA=false
+           IGNORE_MSG_CPPCHECK=true
+           IGNORE_MSG_CLANG_FORMAT=false
+           IGNORE_MSG_PEP8=false
+
+           # The script is called within the Travis CI environment and thus can not be run incremental.
+           RUNS_ON_TRAVIS=true
+           INCREMENTAL=false
+
+           chmod +x extras/static_code_analysis.sh
+           ./extras/static_code_analysis.sh "$RUNS_ON_TRAVIS" "$INCREMENTAL" "$file_names" "$NEST_VPATH" \
+           "$VERA" "$CPPCHECK" "$CLANG_FORMAT" "$PEP8" \
+           "$PERFORM_VERA" "$PERFORM_CPPCHECK" "$PERFORM_CLANG_FORMAT" "$PERFORM_PEP8" \
+           "$IGNORE_MSG_VERA" "$IGNORE_MSG_CPPCHECK" "$IGNORE_MSG_CLANG_FORMAT" "$IGNORE_MSG_PEP8"
+
+           exit $?
+           
+       - if: ${{ matrix.xNEST_BUILD_TYPE == 'MINIMAL' }}
+         #run: echo "MPI Only Build"
+         #with: ${{ env.xMPI }}
+         run: |
+           chmod +x extras/staticbuild.sh
+           ./extras/staticbuild.sh    
          
        #- name: MPI
          #run: echo "MPI BUILD"
